host: 127.0.0.1:8080
secret: superSecret
tokenTTL: 30m
storage:
    postgres:
        dsn: postgres://postgres:postgres@0.0.0.0:5432/keeper?sslmode=disable
        sourceMigrations: "file://./migrations/server"