name: lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  golangci:
    name: golangci-lint
    strategy:
      matrix:
        go-version: [1.21.x]
        os: [ubuntu-latest]
    env:
      OS: ${{ matrix.os }}
      GO: ${{ matrix.go-version }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.55.2